#!/usr/bin/env bash
#
# Global settings and values

set -e
set -o errexit
set -o errtrace

cd $(dirname $0)/..
ROOT_DIR=$PWD

IMAGE_NAME=github-webhook
IMAGE_TAG=latest
LOCAL_CERTS_DIR=/usr/local/share/ca-certificates
APP_NAME=$IMAGE_NAME
APP_BUILDSTAMP=$(date -u +%Y%m%d%H%M%S)

CONFIG_YML=config.concourse.yml
DEBUG=true

####################

DOWNLOAD_DIR=$ROOT_DIR/.downloads
STAGING_DIR=$ROOT_DIR/.staging

#Configures which tools are installed
WEBHOOK_TOOLS=(
    "certificates"
    "cf"
    "fly"
    "phantomjs"
)

#You can change this url to match your Concourse CI server
#For example http://XXXX.somewhere.com/api/v1/cli?arch=amd64&platform=linux
FLY_TOOL_LOCATION="https://ci.concourse.ci/api/v1/cli?arch=amd64&platform=linux"

###################

if [ "$CF_APP_NAME" == "" ]; then
    CF_APP_NAME=$APP_NAME
fi

if [ "$CF_MEMORY" == "" ]; then
    CF_MEMORY="128M"
fi

if [ "$CF_DISK" == "" ]; then
    CF_DISK="256M"
fi

if [ "$CF_INSTANCES" == "" ]; then
    CF_INSTANCES="1"
fi

###################

if builtin type -p git &>/dev/null; then

    if [ -f "$ROOT_DIR/.git/HEAD" ]; then

        GIT_COMMIT=$(git log --format="%H" -n 1 -q | cut -c1-12)
        GIT_DIRTY=$(test -n "`git status --porcelain`" && echo "+CHANGES" || true)
        APP_VERSION=$(git describe --tags 2> /dev/null | head -n 1 | echo "")
        LD_FLAGS="-X main.GitCommit=$GIT_COMMIT$GIT_DIRTY"

        if [ "$APP_VERSION" != "" ]; then
            LD_FLAGS="$LD_FLAGS -X main.Version=$APP_VERSION"
        fi
    fi
fi

if [ "$APP_BUILDSTAMP" != "" ]; then
    LD_FLAGS="$LD_FLAGS -X main.BuildStamp=$APP_BUILDSTAMP"
fi


