#!/usr/bin/env bash

set -e
set -o errexit
set -o errtrace

# default executable locations
phantomjs_executable=phantomjs
fly_executable=fly

# If the runtime is a Cloud Foundry application instance,
# reference the full paths to the deployed `phantomjs`
# and `fly` executables.
if [[ "$CF_INSTANCE_GUID" != "" ]]; then
    phantomjs_executable=/app/tools/phantomjs/bin/phantomjs
    fly_executable=/app/tools/fly/fly
fi

cd $(dirname $0)/..

if [[ "$GITHUB_LDAP_PASSWORD" == "" ]]; then
    echo "ERROR: GITHUB_LDAP_PASSWORD not defined"
    exit 1
fi

if [[ "$GITHUB_LDAP_USERNAME" == "" ]]; then
    echo "ERROR: GITHUB_LDAP_USERNAME not defined"
    exit 1
fi

if [[ "$CONCOURSE_TARGET" == "" ]]; then
    echo "ERROR: CONCOURSE_TARGET not defined"
    exit 1
fi

if [[ "$CONCOURSE_URL" == "" ]]; then
    echo "ERROR: CONCOURSE_URL not defined"
    exit 1
fi

echo "triggered by $1"

echo "logging into $CONCOURSE_URL ($CONCOURSE_TARGET) as $GITHUB_LDAP_USERNAME"

token=$($phantomjs_executable --load-images=no --ignore-ssl-errors=yes --debug=no --ssl-protocol=tlsv1 oauth2.js)

echo $token | $fly_exectuable -t $CONCOURSE_TARGET login -c $CONCOURSE_URL &> /dev/null

$fly_executable -t $CONCOURSE_TARGET sync

echo "triggering job $2"
$fly_exectuable -t $CONCOURSE_TARGET trigger-job --job $2
